fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: noreply@test.com
        sender_name: Symfony-hackathon-starter
    registration:
        confirmation:
            enabled: false
    resetting:
        email:
            from_email:
                address:        resetting@test.com
                sender_name:    Symfony-hackathon-starter